/* City/state-aware search. Local Natural Earth index works without the geocoder. */
(function(root){
 const states={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.']/g,'').replace(/[^a-z0-9]+/g,' ').trim();
 const cityKey=s=>({nyc:'new york','new york city':'new york','washington dc':'washington','st louis':'saint louis','st paul':'saint paul'}[norm(s)]||norm(s));
 const stateName=s=>states[String(s).replace(/\./g,'').toUpperCase()]||Object.values(states).find(v=>norm(v)===norm(s));
 const aliases={nyc:['New York','New York'],sf:['San Francisco','California'],la:['Los Angeles','California'],dc:['Washington','District of Columbia'],'washington dc':['Washington','District of Columbia']};
 function parse(text){let q=text.trim(),state=null,invalid=false;const parts=q.split(',').map(s=>s.trim()).filter(Boolean);if(parts.length>1){q=parts[0];if(!['us','usa','united states','united states of america'].includes(norm(parts[1]))){state=stateName(parts[1]);invalid=!state}}else{for(const suffix of [...Object.values(states),...Object.keys(states)].sort((a,b)=>b.length-a.length)){const n=norm(q),end=norm(suffix);if(n.endsWith(' '+end)){const words=end.split(' ').length;const raw=q.trim().split(/\s+/);q=raw.slice(0,-words).join(' ');state=stateName(suffix);break}}}const alias=aliases[norm(q)];if(alias){q=alias[0];state=state||alias[1]}return {city:q,state,invalid,key:cityKey(q),unsupported:['Alaska','Hawaii'].includes(state)}}
 function rank(query,local,remote=[]){const candidates=[...remote.filter(p=>p.country_code==='US'&&/^PPL(?:A[1-5]?|C|G)?$/.test(p.feature_code||'')).map(p=>({city:p.name,state:p.admin1,county:p.admin2,lat:p.latitude,lon:p.longitude,population:p.population||0,elevation:p.elevation||0,source:'GeoNames'})),...local.map(p=>({...p,city:p.name,source:'Natural Earth'}))];const filtered=candidates.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&p.lat>=24&&p.lat<=50&&p.lon>=-126&&p.lon<=-66&&(!query.state||norm(p.state)===norm(query.state))&&(cityKey(p.city)===query.key||cityKey(p.city).startsWith(query.key)));const score=p=>(cityKey(p.city)===query.key?1e9:0)+Math.min(p.population||0,5e7);filtered.sort((a,b)=>score(b)-score(a)||a.city.localeCompare(b.city)||a.state.localeCompare(b.state));const found=[];for(const p of filtered){const prior=found.find(x=>cityKey(x.city)===cityKey(p.city)&&norm(x.state)===norm(p.state)&&Math.hypot(x.lat-p.lat,x.lon-p.lon)<.12);if(prior){if(p.source==='GeoNames'&&prior.source!=='GeoNames')Object.assign(prior,p);continue}found.push(p)}return found.slice(0,10)}
 function attach({form,input,results,getLocal,onSelect}){let serial=0,controller,timer,found=[],active=-1;const cache=new Map();input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls',results.id);results.setAttribute('role','listbox');results.setAttribute('aria-label','Matching U.S. cities');
 function close(){serial++;clearTimeout(timer);controller?.abort();results.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1}
 function choose(index){const p=found[index];if(!p)return;close();input.value=p.city+', '+p.state;onSelect({name:p.city+' · '+p.state,lat:p.lat,lon:p.lon,elevation:p.elevation||0});input.blur()}
 function render(rows,message){const previous=found[active];found=rows;active=previous?rows.findIndex(p=>cityKey(p.city)===cityKey(previous.city)&&norm(p.state)===norm(previous.state)):-1;results.replaceChildren();input.removeAttribute('aria-activedescendant');results.hidden=false;input.setAttribute('aria-expanded','true');for(const [i,p] of rows.entries()){const btn=document.createElement('button');btn.type='button';btn.id='city-option-'+i;btn.setAttribute('role','option');btn.setAttribute('aria-selected',String(i===active));if(i===active)input.setAttribute('aria-activedescendant',btn.id);btn.textContent=p.city;const detail=document.createElement('small');detail.textContent=[p.state,p.county,'United States'].filter(Boolean).join(' · ');btn.append(detail);btn.onclick=()=>choose(i);results.append(btn)}const note=document.createElement('p');note.className='search-note';note.setAttribute('role','status');note.textContent=message||'Choose a city. Add a state to narrow the results.';results.append(note)}
 async function search(){const query=parse(input.value);controller?.abort();controller=new AbortController();const own=controller,run=++serial;if(query.key.length<2){close();return}if(query.invalid){render([],'Use a full state name or two-letter code, e.g. Portland, OR.');return}if(query.unsupported){render([],'This forest map covers the contiguous United States.');return}const local=rank(query,getLocal());render(local,local.length?'Choose a city, or add a state to narrow the results.':'Searching U.S. cities…');try{const name=query.city+(query.state?', '+query.state:'');let data=cache.get(name);if(!data){const params=new URLSearchParams({name,count:'100',language:'en',countryCode:'US'});const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+params,{signal:own.signal});if(!r.ok)throw Error('Geocoder unavailable');data=await r.json();cache.set(name,data);if(cache.size>40)cache.delete(cache.keys().next().value)}if(serial!==run||own.signal.aborted)return;const rows=rank(query,getLocal(),data.results||[]);render(rows,rows.length?undefined:'No matching city. Try its full name and state, e.g. Boston, MA.')}catch(e){if(e.name==='AbortError'||serial!==run)return;render(local,local.length?'Showing saved city matches; live search is unavailable.':'Live search is unavailable. Try a major city or select a location on the map.')}}
 form.onsubmit=e=>{e.preventDefault();clearTimeout(timer);if(active>=0)choose(active);else search()};input.oninput=()=>{serial++;controller?.abort();clearTimeout(timer);found=[];active=-1;results.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');if(input.value.trim().length>=2)timer=setTimeout(search,300)};input.onkeydown=e=>{if(e.key==='Escape'){close();return}if(['ArrowDown','ArrowUp'].includes(e.key)&&found.length&&!results.hidden){e.preventDefault();active=active<0?(e.key==='ArrowDown'?0:found.length-1):(active+(e.key==='ArrowDown'?1:-1)+found.length)%found.length;results.querySelectorAll('[role=option]').forEach((n,i)=>n.setAttribute('aria-selected',String(i===active)));const el=results.querySelector('#city-option-'+active);input.setAttribute('aria-activedescendant',el.id);el.scrollIntoView({block:'nearest'})}};document.addEventListener('click',e=>{if(!form.contains(e.target))close()});return {close,search};
 }
 root.CitySearch={parse,rank,attach};
})(typeof window==='undefined'?globalThis:window);
