/* Generated botanical sprites visualize USFS relative basal area, not real tree coordinates. */
(function(){
const boxes=[[0,25,342,464],[343,24,277,465],[622,24,282,465],[918,25,256,464],[1140,52,396,440],[0,499,320,470],[548,523,310,447],[332,496,230,473],[858,545,311,425],[1164,566,372,404]];
const hash=(x,y,z=0)=>{let n=Math.imul(x^Math.imul(y,374761393)^Math.imul(z,668265263),1274126177);n=(n^(n>>>13));return ((Math.imul(n,1274126177)^(n>>>16))>>>0)/4294967296};
const image=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Image unavailable: '+src));im.src=src});
class TreeSprites{
 async load(species){this.species=species;this.cache=new Map();const im=await image('assets/trees.png');this.base=boxes.map(([x,y,w,h])=>{const c=document.createElement('canvas');c.width=180;c.height=240;const ctx=c.getContext('2d',{willReadFrequently:true});const scale=Math.min(176/w,236/h),dw=w*scale,dh=h*scale;ctx.drawImage(im,x,y,w,h,(180-dw)/2,240-dh,dw,dh);const pixels=ctx.getImageData(0,0,180,240),a=pixels.data;for(let i=0;i<a.length;i+=4){const spill=Math.min(a[i],a[i+2])-a[i+1];if(spill>32)a[i+3]=0;else if(spill>5){a[i+3]*=1-(spill-5)/27;a[i]=Math.min(a[i],a[i+1]+5);a[i+2]=Math.min(a[i+2],a[i+1]+5)}}ctx.putImageData(pixels,0,0);return pixels});return this}
 get(index,progress){const step=Math.round(AutumnModel.clamp(progress)*24),key=index*25+step;if(this.cache.has(key))return this.cache.get(key);const raw=this.base[index],c=document.createElement('canvas');c.width=180;c.height=240;const ctx=c.getContext('2d'),out=ctx.createImageData(180,240);out.data.set(raw.data);const a=out.data,target=AutumnModel.color(this.species[index],step/24);for(let i=0;i<a.length;i+=4){if(!a[i+3])continue;const r=a[i],g=a[i+1],b=a[i+2];const leaf=g>b*1.17&&g>r*.83;if(leaf){const lum=(r*.25+g*.62+b*.13)/100;const texture=.35+lum*.72;a[i]=Math.min(255,target[0]*texture);a[i+1]=Math.min(255,target[1]*texture);a[i+2]=Math.min(255,target[2]*texture);if(step>20){const p=i/4,noise=hash(p%180,Math.floor(p/180),index);if(noise<(step-20)*.11)a[i+3]*=.14}}}ctx.putImageData(out,0,0);this.cache.set(key,c);return c}
}
const ForestLayer=L.Layer.extend({
 initialize(opts){this.options=opts;this.trees=[];this.quality=1;this.lastDrawMs=0},
 onAdd(map){this._map=map;this.canvas=L.DomUtil.create('canvas','forest-canvas');map.getPane('autumn').appendChild(this.canvas);this.canvas.setAttribute('aria-hidden','true');map.on('moveend zoomend resize',this.redraw,this);this.redraw()},
 onRemove(map){map.off('moveend zoomend resize',this.redraw,this);cancelAnimationFrame(this.frame);this.canvas.remove()},
 redraw(){cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>this.draw());return this},
 sample(lon,lat,index){const m=this.options.meta,x=(lon-m.west)/m.step-.5,y=(m.north-lat)/m.step-.5;if(x<0||y<0||x>=m.width-1||y>=m.height-1)return 0;const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,w=m.width*10;const a=this.options.raster;const at=(dx,dy)=>a[((iy+dy)*w+index*m.width+ix+dx)*4]/255;return at(0,0)*(1-fx)*(1-fy)+at(1,0)*fx*(1-fy)+at(0,1)*(1-fx)*fy+at(1,1)*fx*fy},
 atLocation(lon,lat){return this.options.species.map((s,i)=>({s,value:this.sample(lon,lat,i)})).filter(x=>x.value>.001).sort((a,b)=>b.value-a.value)},
 draw(){if(!this._map)return;const started=performance.now(),map=this._map,size=map.getSize(),dpr=Math.min(devicePixelRatio||1,2),z=map.getZoom(),ctx=this.canvas.getContext('2d');L.DomUtil.setPosition(this.canvas,map.containerPointToLayerPoint([0,0]));this.canvas.style.width=size.x+'px';this.canvas.style.height=size.y+'px';this.canvas.width=size.x*dpr;this.canvas.height=size.y*dpr;ctx.scale(dpr,dpr);const state=this.options.state(),all=this.options.species,selected=all.map((s,i)=>({s,i})).filter(({s})=>state.enabled.has(s.id));this.trees=[];if(!selected.length){this.options.onDraw?.(0);return;}const spacing=(z<=4?9:z<=6?13:z<=8?22:30)/Math.sqrt(this.quality),origin=map.getPixelBounds().min,margin=150;const minX=Math.floor((origin.x-margin)/spacing),maxX=Math.ceil((origin.x+size.x+margin)/spacing),minY=Math.floor((origin.y-margin)/spacing),maxY=Math.ceil((origin.y+size.y+margin)/spacing),world=256*2**z;
 for(let gy=minY;gy<=maxY;gy++)for(let gx=minX;gx<=maxX;gx++){const wx=(gx+hash(gx,gy,5+z)*.9)*spacing,wy=(gy+hash(gx,gy,19+z)*.9)*spacing,lon=wx/world*360-180,lat=Math.atan(Math.sinh(Math.PI*(1-2*wy/world)))*180/Math.PI;if(lon<-126||lon>-66||lat<24||lat>50)continue;const weights=selected.map(({i})=>this.sample(lon,lat,i)),sum=weights.reduce((a,b)=>a+b,0);if(sum<.008||hash(gx,gy,31+z)>1-Math.exp(-sum*3.2))continue;let pick=hash(gx,gy,73+z)*sum,choice=selected.at(-1);for(let n=0;n<weights.length;n++){pick-=weights[n];if(pick<=0){choice=selected[n];break}}const variation=hash(gx,gy,97+z),h=(z<=4?30:z<=6?47:z<=8?76:112)*(.74+variation*.5),x=wx-origin.x,y=wy-origin.y;const p=AutumnModel.progress(choice.s,state.day+(variation-.5)*7,lat,lon);this.trees.push({x,y,h,w:h*.75,i:choice.i,lat,lon,p,seed:variation})}
 this.trees.sort((a,b)=>a.y-b.y||a.x-b.x);const cap=innerWidth<650?2400:4500;if(this.trees.length>cap){const stride=this.trees.length/cap;this.trees=this.trees.filter((_,i)=>Math.floor(i/stride)!==Math.floor((i-1)/stride))}ctx.globalAlpha=state.opacity??1;for(const t of this.trees){ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(t.x+3,t.y-2,t.w*.32,t.h*.055,-.2,0,Math.PI*2);ctx.fill();ctx.drawImage(this.options.sprites.get(t.i,t.p),t.x-t.w/2,t.y-t.h,t.w,t.h)}ctx.globalAlpha=1;this.lastDrawMs=performance.now()-started;this.options.onDraw?.(this.trees.length);
 },
 hit(point){for(let i=this.trees.length-1;i>=0;i--){const t=this.trees[i];if(point.x>t.x-t.w*.38&&point.x<t.x+t.w*.38&&point.y>t.y-t.h*.9&&point.y<t.y-t.h*.1)return t}return null}
});
window.ForestArt={TreeSprites,ForestLayer,loadRaster:async()=>{const [meta,im]=await Promise.all([fetch('data/forest-meta.json').then(r=>{if(!r.ok)throw Error('Forest metadata unavailable');return r.json()}),image('data/forest-abundance.png')]);if(im.width!==meta.width*10||im.height!==meta.height)throw Error('Invalid forest raster dimensions');const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);return {meta,raster:ctx.getImageData(0,0,c.width,c.height).data}}};
})();
